# Generated by Django 3.1.1 on 2020-09-21 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='name',
            field=models.TextField(default='TEST'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='collection',
            name='citations',
            field=models.ManyToManyField(to='collection.Citation'),
        ),
    ]
