# Generated by Django 3.1.1 on 2020-09-21 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_auto_20200921_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='citation',
            name='citation_type',
            field=models.CharField(choices=[('DC', 'Data Citation'), ('PC', 'Publication Citation'), ('TC', 'TCIA Citation')], default='PC', max_length=2),
        ),
        migrations.AlterField(
            model_name='citation',
            name='link',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='collection',
            name='citations',
            field=models.ManyToManyField(blank=True, to='collection.Citation'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
