# Generated by Django 3.1.1 on 2020-09-21 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_auto_20200921_1853'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='image_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='image_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='participant_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='series_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='study_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='modalities',
            field=models.ManyToManyField(blank=True, to='collection.Modality'),
        ),
    ]
