# Generated by Django 3.1.1 on 2020-09-21 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_auto_20200921_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='image_size',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
