# Generated by Django 3.1.1 on 2020-09-21 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0005_auto_20200921_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='short_name',
            field=models.CharField(default='ACRIN', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
