# Generated by Django 3.1.1 on 2020-09-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0006_collection_short_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('description', models.TextField(blank=True)),
                ('updated', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='uploads',
            field=models.ManyToManyField(blank=True, to='collection.Upload'),
        ),
    ]
