# Generated by Django 3.1.1 on 2020-09-22 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0007_auto_20200921_1953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='image_count',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='image_size',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='modalities',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='participant_count',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='series_count',
        ),
        migrations.RemoveField(
            model_name='collection',
            name='study_count',
        ),
        migrations.AlterField(
            model_name='collection',
            name='short_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.CreateModel(
            name='ImageCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('participant_count', models.IntegerField(blank=True, null=True)),
                ('study_count', models.IntegerField(blank=True, null=True)),
                ('series_count', models.IntegerField(blank=True, null=True)),
                ('image_count', models.IntegerField(blank=True, null=True)),
                ('image_size', models.FloatField(blank=True, null=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection')),
                ('modalities', models.ManyToManyField(blank=True, to='collection.Modality')),
            ],
        ),
    ]
