# Generated by Django 3.1.1 on 2020-09-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0008_auto_20200922_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Download',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('description', models.TextField(blank=True)),
                ('updated', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownloadVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('version', models.IntegerField()),
                ('updated', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='collection',
            name='uploads',
        ),
        migrations.DeleteModel(
            name='Upload',
        ),
        migrations.AddField(
            model_name='downloadversion',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.collection'),
        ),
        migrations.AddField(
            model_name='download',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.downloadversion'),
        ),
        migrations.AlterUniqueTogether(
            name='downloadversion',
            unique_together={('collection', 'version')},
        ),
    ]
