# Generated by Django 3.1.1 on 2020-09-22 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0010_auto_20200922_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='download',
            name='download_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
